name: example
description: An example on how to use driver extensions

version: 1.0.0+1

environment:
  sdk: '>=2.9.0-18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.9.4
  driver_extensions:
    path: ../

flutter:

  uses-material-design: true