name: driver_extensions
description: A set of Flutter Driver extension methods to make driver tests easier to write and maintain.
version: 2.0.0-nullsafety.1
homepage: https://github.com/tomaszpolanski/driver_extensions

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  fast_flutter_driver: ^3.0.0
  stack_trace: ^1.10.0
