name: driver_extensions
description: A set of Flutter Driver extension methods to make driver tests easier to write and maintain.
version: 1.2.0
homepage: https://github.com/tomaszpolanski/driver_extensions

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  colorize: ^2.0.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
  fast_flutter_driver: ^0.1.1+2
  stack_trace: ^1.9.3
