name: driver_extensions
description: A set of Flutter Driver extension methods to make driver tests easier to write and maintain.
version: 1.2.0+1
homepage: https://github.com/tomaszpolanski/driver_extensions

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  colorize: ^2.0.0
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety.12
  fast_flutter_driver: ^0.1.1+2
  stack_trace: ^1.10.0-nullsafety.6
