// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../../test_driver/scrolling_test.dart' as test_driver_scrolling;
import '../../test_driver/tapping_test.dart' as test_driver_tapping;

void main(List<String> args) {
  test_driver_scrolling.main(args);
  test_driver_tapping.main(args);
}
