name: Build

on: [ push, pull_request ]

jobs:
  build_flutter_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: [ "beta" ]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: flutter test
        working-directory: ${{ matrix.package }}
